framework:
    cache:
        pools:
            cache.telegram_bot:
                adapter: cache.adapter.redis_tag_aware
                provider: app.redis_provider
                tags: true

services:
    app.redis_provider:
        class: \Redis
        factory:
            ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - '%env(resolve:REDIS_URL)%'
            - { retry_interval: 2, timeout: 10 }
