framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        mapping:
            paths: ['%kernel.project_dir%/config/validation/']
        auto_mapping:
            App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
