services:
  ###> doctrine/doctrine-bundle ###
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/default.conf:ro
      - .:/var/www/project:ro
    ports:
      - ${WEB_HOST_PORT}:80
    restart: always
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker/php
    environment:
      - XDEBUG_PORT=${XDEBUG_PORT}
      - PHP_CS_FIXER_IGNORE_ENV=${PHP_CS_FIXER_IGNORE_ENV}
    volumes:
      - .:/var/www/project/
      - /var/www/project/var/
      - /var/www/project/vendor/
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    container_name: redis
    build:
      context: ./docker/redis
    # environment:
    #   - SKIP_FIX_PERMS=1
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis-data:/data
      - ./docker/redis/log:/var/log/redis
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  # mailer:
  #   container_name: mailer
  #   image: axllent/mailpit
  #   ports:
  #     - "1025"
  #     - "8025"
  #   environment:
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

volumes:
  ###> doctrine/doctrine-bundle ###
  postgres-data:
  ###< doctrine/doctrine-bundle ###
  redis-data:
