App\Entity\Booking\Booking:
    properties:
        phoneNumber:
            - NotBlank: ~
            - Length:
                  min: 10
                  max: 15
        houseId:
            - NotBlank: ~
            - Type: integer
        comment:
            - Length:
                  max: 255
