App\Entity\TelegramBotUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: telegramId
              message: 'there is already an account with this telegram id.'
    properties:
        telegramId:
            - Type:
                  type: integer
            - NotBlank: ~
            - Range:
                  min: 1
                  max: 2147483647
        username:
            - Type:
                  type: string
            - Length:
                  min: 1
                  max: 255
        firstName:
            - Type:
                  type: string
            - Length:
                  min: 1
                  max: 255
        lastName:
            - Type:
                  type: string
            - Length:
                  min: 1
                  max: 255
        phoneNumber:
            - Type:
                  type: string
            - Regex:
                  # TODO: handle international phone numbers
                  pattern: '/^\+7\d{10}$/'
                  message: 'Phone number must start with +7 and contain exactly 10 digits after that.'
