App\Entity\House:
    properties:
        address:
            - NotBlank: ~
            - Regex:
                  pattern: '/^(\d{1,}) [a-zA-Z0-9\s]+(\,)? [a-zA-Z]+(\,)? [A-Z]{2} [0-9]{5,6}$/'
                  message: 'Address must be in the format: 123 Main St, City, ST 12345'
            - Length:
                  max: 255
        price:
            - NotBlank: ~
            - Type: integer
            - PositiveOrZero: ~
