App\Entity\SummerHouse:
    properties:
        bedrooms:
            - Type: integer
            - NotBlank:
                  allowNull: true
            - PositiveOrZero: ~
        distanceFromSea:
            - Type: integer
            - NotBlank:
                  allowNull: true
            - PositiveOrZero: ~
        hasShower:
            - Type: bool
        hasBathroom:
            - Type: bool
