App\Entity\Booking:
    properties:
        user:
            - Type:
                  type: App\Entity\User
        telegramBotUser:
            - Type:
                  type: App\Entity\TelegramBotUser
        house:
            - NotBlank: ~
            - Type:
                  type: App\Entity\House
        comment:
            - Length:
                  max: 255
        startDate:
            - Type:
                  type: \DateTimeInterface
            - NotBlank: ~

        endDate:
            - Type:
                  type: \DateTimeInterface
            - NotBlank: ~
