services:
  nginx:
    build:
      context: ../.
      dockerfile: ./.docker/dev/nginx/Dockerfile.nginx.dev
    env_file:
      - ./dev/.env.dev
    volumes:
      - ./../backend/public:/var/www/public:rw
    ports:
      - 80:80
    restart: always
    depends_on:
      - php

  php:
    build:
      context: ../.
      dockerfile: ./.docker/dev/php/Dockerfile.php.dev
    volumes:
      - ./../backend:/var/www/app/
      - /var/www/app/var
      - /var/www/app/vandor
    env_file:
      - ./dev/.env.dev
    depends_on:
      - postgres

  ###> doctrine/doctrine-bundle ###
  postgres:
    build:
      context: ../.
      dockerfile: ./.docker/dev/postgres/Dockerfile.postgres.dev
    env_file:
      - ./../backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
  ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  postgres_data:
  ###< doctrine/doctrine-bundle ###
