doctrine:
    orm:
        mappings:
            Booking:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Entity/Booking"
                prefix: 'App\Entity\Booking'
